name: Release pull request canbe merge by GitHub Actions

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - release

jobs:
  release-pr-canbe-merge-by-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
